version: '3.8'

services:
  app:
    container_name: todo-app-api
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - todo-app-network

    ports:
    - "8080:8080"

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

    # Runs app on the same network as the application
    network_mode: service:app

    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

networks:
  default:
    external:
      name: bridge
  todo-app-network:
    name: todo-app-network
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: "172.20.100.0/24"

volumes:
  mongodb-data: